# app/core/permissions/organizacion.py

from enum import Enum

class PermisosPuestos(str, Enum):
    """Permisos específicos para el módulo de puestos"""
    CREAR = "PUESTOS_CREAR"
    LEER = "PUESTOS_LEER"
    ACTUALIZAR = "PUESTOS_ACTUALIZAR"
    ELIMINAR = "PUESTOS_ELIMINAR"
    VER_TODOS = "PUESTOS_VER_TODOS"
    CAMBIAR_ESTADO = "PUESTOS_CAMBIAR_ESTADO"
    ASIGNAR_PERMISOS = "PUESTOS_ASIGNAR_PERMISOS"
    VER_ESTRUCTURA = "PUESTOS_VER_ESTRUCTURA"
    GESTIONAR_JERARQUIA = "PUESTOS_GESTIONAR_JERARQUIA"

class PermisosUnidadOrganica(str, Enum):
    """Permisos específicos para el módulo de unidades orgánicas"""
    CREAR = "UNIDAD_ORGANICA_CREAR"
    LEER = "UNIDAD_ORGANICA_LEER"
    ACTUALIZAR = "UNIDAD_ORGANICA_ACTUALIZAR"
    ELIMINAR = "UNIDAD_ORGANICA_ELIMINAR"
    VER_TODAS = "UNIDAD_ORGANICA_VER_TODAS"
    CAMBIAR_ESTADO = "UNIDAD_ORGANICA_CAMBIAR_ESTADO"
    GESTIONAR_ESTRUCTURA = "UNIDAD_ORGANICA_GESTIONAR_ESTRUCTURA"
    VER_ORGANIGRAMA = "UNIDAD_ORGANICA_VER_ORGANIGRAMA"
    REORDENAR = "UNIDAD_ORGANICA_REORDENAR"

class PermisosOrganizacion(str, Enum):
    """Permisos generales para el módulo de organización"""
    VER_ORGANIGRAMA_COMPLETO = "ORGANIZACION_VER_ORGANIGRAMA_COMPLETO"
    GESTIONAR_ESTRUCTURA_COMPLETA = "ORGANIZACION_GESTIONAR_ESTRUCTURA_COMPLETA"
    EXPORTAR_ORGANIGRAMA = "ORGANIZACION_EXPORTAR_ORGANIGRAMA"
    CONFIGURAR_JERARQUIAS = "ORGANIZACION_CONFIGURAR_JERARQUIAS"
    REPORTES_ORGANIZACION = "ORGANIZACION_REPORTES"