"""Agregar foto_perfil_url a usuarios

Revision ID: 364b538a7358
Revises: f5bcd1f8d9f1
Create Date: 2025-06-17 17:53:30.929508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364b538a7358'
down_revision: Union[str, Sequence[str], None] = 'f5bcd1f8d9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('foto_perfil_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'foto_perfil_url')
    # ### end Alembic commands ###
