"""Initial migration

Revision ID: d11096f64d2e
Revises: 
Create Date: 2025-06-28 19:46:01.034648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11096f64d2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades_organicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad_padre_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['seguridad.usuarios.id'], name='fk_unidad_creado_por', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['unidad_padre_id'], ['organizacion.unidades_organicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla'),
    sa.UniqueConstraint('uuid'),
    schema='organizacion'
    )
    op.create_index(op.f('ix_organizacion_unidades_organicas_id'), 'unidades_organicas', ['id'], unique=False, schema='organizacion')
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('tipo_permiso', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_permisos_id'), 'permisos', ['id'], unique=False, schema='seguridad')
    op.create_table('registro_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.String(length=50), nullable=True),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), nullable=True),
    sa.Column('hash_bloque', sa.String(length=64), nullable=True),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['seguridad.usuarios.id'], name='fk_evento_usuario', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_registro_eventos_id'), 'registro_eventos', ['id'], unique=False, schema='seguridad')
    op.create_table('puestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad_organica_id', sa.Integer(), nullable=False),
    sa.Column('puesto_superior_id', sa.Integer(), nullable=True),
    sa.Column('nivel_jerarquico', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['seguridad.usuarios.id'], name='fk_puesto_creado_por', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['puesto_superior_id'], ['organizacion.puestos.id'], ),
    sa.ForeignKeyConstraint(['unidad_organica_id'], ['organizacion.unidades_organicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('uuid'),
    schema='organizacion'
    )
    op.create_index(op.f('ix_organizacion_puestos_id'), 'puestos', ['id'], unique=False, schema='organizacion')
    op.create_table('puesto_permisos',
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['seguridad.usuarios.id'], name='fk_permiso_usuario', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['seguridad.permisos.id'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['organizacion.puestos.id'], ),
    sa.PrimaryKeyConstraint('puesto_id', 'permiso_id'),
    schema='seguridad'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('puesto_id', sa.Integer(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puesto_id'], ['organizacion.puestos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_usuarios_id'), 'usuarios', ['id'], unique=False, schema='seguridad')
    op.create_table('sesiones_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_sesion', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['seguridad.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_sesion'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_sesiones_usuario_id'), 'sesiones_usuario', ['id'], unique=False, schema='seguridad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguridad_sesiones_usuario_id'), table_name='sesiones_usuario', schema='seguridad')
    op.drop_table('sesiones_usuario', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_usuarios_id'), table_name='usuarios', schema='seguridad')
    op.drop_table('usuarios', schema='seguridad')
    op.drop_table('puesto_permisos', schema='seguridad')
    op.drop_index(op.f('ix_organizacion_puestos_id'), table_name='puestos', schema='organizacion')
    op.drop_table('puestos', schema='organizacion')
    op.drop_index(op.f('ix_seguridad_registro_eventos_id'), table_name='registro_eventos', schema='seguridad')
    op.drop_table('registro_eventos', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_permisos_id'), table_name='permisos', schema='seguridad')
    op.drop_table('permisos', schema='seguridad')
    op.drop_index(op.f('ix_organizacion_unidades_organicas_id'), table_name='unidades_organicas', schema='organizacion')
    op.drop_table('unidades_organicas', schema='organizacion')
    # ### end Alembic commands ###
