"""Migración inicial SGD-Colca

Revision ID: f5bcd1f8d9f1
Revises: 
Create Date: 2025-06-17 17:48:05.323531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5bcd1f8d9f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_documento',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('prefijo_correlativo', sa.String(length=10), nullable=False),
    sa.Column('requiere_cargo', sa.Boolean(), nullable=True),
    sa.Column('plantilla_gdoc_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('unidades_organicas',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('unidad_padre_id', sa.UUID(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_padre_id'], ['unidades_organicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('puestos',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('unidad_organica_id', sa.UUID(), nullable=False),
    sa.Column('nivel_jerarquico', sa.Integer(), nullable=False),
    sa.Column('puede_firmar', sa.Boolean(), nullable=True),
    sa.Column('puede_aprobar', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_organica_id'], ['unidades_organicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('puesto_id', sa.UUID(), nullable=True),
    sa.Column('es_superadmin', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['puesto_id'], ['puestos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_document_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('hash_anterior', sa.String(length=256), nullable=True),
    sa.Column('hash_actual', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_tdi',
    sa.Column('numero_correlativo', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento_id', sa.UUID(), nullable=False),
    sa.Column('usuario_emisor_id', sa.UUID(), nullable=False),
    sa.Column('unidad_emisora_id', sa.UUID(), nullable=False),
    sa.Column('destinatario_interno', sa.String(length=200), nullable=True),
    sa.Column('destinatario_externo', sa.Text(), nullable=True),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('gdoc_id', sa.String(length=200), nullable=True),
    sa.Column('gdoc_url', sa.Text(), nullable=True),
    sa.Column('pdf_drive_id', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('requiere_aprobacion', sa.Boolean(), nullable=True),
    sa.Column('aprobado_por_id', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('confidencial', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['unidad_emisora_id'], ['unidades_organicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_emisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_correlativo')
    )
    op.create_table('expedientes_mesa_partes',
    sa.Column('numero_expediente', sa.String(length=50), nullable=False),
    sa.Column('solicitante_nombres', sa.String(length=200), nullable=False),
    sa.Column('solicitante_apellidos', sa.String(length=200), nullable=True),
    sa.Column('solicitante_dni', sa.String(length=8), nullable=True),
    sa.Column('solicitante_email', sa.String(length=255), nullable=True),
    sa.Column('solicitante_telefono', sa.String(length=20), nullable=True),
    sa.Column('solicitante_direccion', sa.Text(), nullable=True),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('tipo_tramite', sa.String(length=100), nullable=True),
    sa.Column('archivos_drive_folder_id', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('unidad_destino_id', sa.UUID(), nullable=True),
    sa.Column('usuario_asignado_id', sa.UUID(), nullable=True),
    sa.Column('ocr_procesado', sa.Boolean(), nullable=True),
    sa.Column('ocr_contenido', sa.Text(), nullable=True),
    sa.Column('entidades_extraidas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_destino_id'], ['unidades_organicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_expediente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expedientes_mesa_partes')
    op.drop_table('documentos_tdi')
    op.drop_table('audit_log')
    op.drop_table('usuarios')
    op.drop_table('puestos')
    op.drop_table('unidades_organicas')
    op.drop_table('tipos_documento')
    # ### end Alembic commands ###
